### ISSUE TITLE
panic when passing -q flag

### ISSUE THREAD

**Issue by zikaeroh** [sonatype-nexus-community/nancy#100]
I mistakenly tried to use `-q` instead of `-quiet` (forgetting the usage). Instead of being told of the bad flag, nancy instead panicked.

```
panic: runtime error: slice bounds out of range [:5] with length 2

goroutine 1 [running]:
github.com/sonatype-nexus-community/nancy/logger.init.0()
	/home/jake/go/pkg/mod/github.com/sonatype-nexus-community/nancy@v0.1.11/logger/logger.go:35 +0x1c5
```

Forgive my deletion of the template; it seemed like a feature request template whereas this is a bug.

I'm on `v0.1.11`.

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
I saw something related to this yesterday and I THINK it's actually from some work I did for logging @bhamail , if that helps!
