### ISSUE TITLE
Add Nancy to Arch User Repository

### ISSUE THREAD

**Issue by mastertinner** [sonatype-nexus-community/nancy#105]
* **What are you trying to do?**

Install Nancy on Arch Linux

* **What feature or behavior is this required for?**

Install it easily

* **How could we solve this issue? (Not knowing is okay!)**

Add Nancy to the Arch User Repository at https://aur.archlinux.org/

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
Hmmmm.

Not even sure how to go about doing this. Wouldn't it be more up to Arch Linux to add Nancy as a tool in it's build process? What can we provide that would make that easier? pkg.tar.gz files?

**Comment by wwannemacher** [comment]
@DarthHater seems you can start here: https://wiki.archlinux.org/index.php/AUR_submission_guidelines

**Comment by DarthHater** [comment]
@mastertinner , I think @bhamail is going to take a look at crafting up some rpms, debs, etc... for Nancy, mainly to serve a couple other purposes. 

More than likely we are going to use: https://github.com/goreleaser/nfpm

It doesn't seem to have support for arch linux packages. Any pro tips on crafting one? Is it much different from a rpm or deb?

**Comment by mastertinner** [comment]
Thanks, everyone! Unfortunately, I'm not a pro either in these tools ;-) I'm very interested in them though so I'll also look into it.

**Comment by mastertinner** [comment]
@DarthHater, I have looked into the process a bit and came up with the following `PKGBUILD` file for the AUR:

```sh
# Maintainer: Tobi Fuhrimann
pkgname=nancy-bin
pkgver=0.2.4
pkgrel=1
pkgdesc="A tool to check for vulnerabilities in your Golang dependencies"
arch=(x86_64 i686)
url="https://github.com/sonatype-nexus-community/nancy"
license=('Apache 2.0')
makedepends=(git go)
provides=(nancy)
_src="${url}/releases/download/v${pkgver}/nancy-linux."
source_x86_64=("${_src}amd64-v${pkgver}.tar.gz")
source_i686=("${_src}386-v${pkgver}.tar.gz")
sha256sums_x86_64=('4467f5b22880fba1b01385f2ba6ca121cbacdac51a52802cd964b66d14c3c169')
sha256sums_i686=('ecdc9025e69504ca1114260883960f1e302f321387a09906fd14eb03ee73f4b9')

package() {
	local x86_64=amd64 i686=386
	install -Dm755 nancy -t "${pkgdir}/usr/bin"
}
```

Would you like me to push it to the AUR (meaning I would be the maintainer) or would you prefer to do it yourself?

**Comment by mastertinner** [comment]
@DarthHater, @wwannemacher, any thoughts?

**Comment by bhamail** [comment]
@mastertinner I'm a bit stalled on the work I was doing to add .apk support to goreleaser, so your approach my be best.
That said, we're doing a "week of innovation" this week, so everybody is pretty much heads down in code until next week. If you don't hear back from us next week, please do ping one more time!

FWIW, I'm not against you being the maintainer.

**Comment by DarthHater** [comment]
Not against you being a maintainer, either! We appreciate the help!!!

**Comment by mastertinner** [comment]
It's done: https://aur.archlinux.org/packages/nancy-bin/ :tada:
