### ISSUE TITLE
Refactor config to use `config *interface{}`

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/nancy#111]
We've been sneaking up on changing the design of the OSSI / IQ config classes to support better reuse/reduced duplication/DRYness.

This Issue exists to track that, and collect ideas on how to git 'er done.

see: [loadConfigFromFile(configLocation string, config *Configuration)](https://github.com/sonatype-nexus-community/nancy/pull/108/files#diff-897b784027d2f601b2cad15ea08d7dc8R108)

see: https://github.com/sonatype-nexus-community/nancy/pull/108/files

Another idea: refactor the `configuration/parse.go -> loadConfigFromFile()` and `loadIQConfigFromFile()` methods to take `io.Reader` - instead of a path `configLocation`. The tests could then easily pass in bytes representing the various file contents. This would also allow the test avoid pesky disk access.

And in the other direction, similarly use `io.Writer` instead of `ConfigLocation` inside `configuration/set.go -> marshallAndWriteToDisk`.

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
I THINK I got a portion of simplifying things in #114 , where I avoided going super nuclear and using an `interface` as a param. Take a gander, bud!

**Comment by bhamail** [comment]
Also fixed by Cobra/Viper conversion. see #161
