### ISSUE TITLE
Cleanup error messaging

### ISSUE THREAD

**Issue by zendern** [sonatype-nexus-community/nancy#115]
* **What are you trying to do?**
Cleanup the output of the cli..... steps to reproduce

1. Install nancy
2. Execute `nancy --version`
3. Notice the no such file or directory error...probably not important to show that error. 
```
nancy --version                                                                                           [4b539b9]
open /Users/zender/.ossindex/.oss-index-config: no such file or directory
0.1.17
build time: 2020-04-10T19:19:52Z
build commit: ddaa880e12e6ce183caa4ff5f55fda1d16b94390
```

* **What feature or behavior is this required for?**
Nothing really .... just cleaning stuff up. 

* **How could we solve this issue? (Not knowing is okay!)**
First thought is to change that to a logLady instead of the println that it probably is.

* **Anything else?**

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
USE THE LOG LADY, SHE HAS THE LOG, SHE IS AWESOME

**Comment by DarthHater** [comment]
I think I cleaned up a part of this in #114 , by removing the `fmt.Println` and just printing to log. Far from the only place we were doing this, but likely worth mentioning.
