### ISSUE TITLE
Integration/Dogfood test for our docker image

### ISSUE THREAD

**Issue by zendern** [sonatype-nexus-community/nancy#119]
* **What are you trying to do?**
We have really good dogfood tests for nancy on itself for the binary build but we do not have that in place for the Docker image. 

* **What feature or behavior is this required for?**
Doing the same dogfood test for the docker image to make sure we dont break it

* **How could we solve this issue? (Not knowing is okay!)**
Probably need to build the Dockerfile at build time (even though it will happen again as part of goreleaser) and then run it and make sure it does what we expect. 

* **Anything else?**

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
This should be FAIRLY easy, a note to anyone who wants to chomp on it:

`      - setup_remote_docker`

Add that to whatever CircleCI job you work on if it's not there, as that puts `docker` inside `docker` like we were all watching Inception :)
