### ISSUE TITLE
JenkinsFile using Makefile

### ISSUE THREAD

**Issue by zendern** [sonatype-nexus-community/nancy#120]
* **What are you trying to do?**
Cleanup a little duplication

* **What feature or behavior is this required for?**
Whats in the .circleci/config.yml and JenkinsFile are pretty similar. And some of it already is in the Makefile. 

* **How could we solve this issue? (Not knowing is okay!)**
So to keep everything more in sync switch over parts that are possible and maybe pull more into the Makefile. 

* **Anything else?**

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
I am 100% into this. I'll have to make sure that Jenkins, my mortal enemy, can handle this, but it should be able to.
