### ISSUE TITLE
Is there a better way to do this test logic??

### ISSUE THREAD

**Issue by zendern** [sonatype-nexus-community/nancy#122]
* **What are you trying to do?**
Checking for if running in a test in production code is kinda icky..... is there a refactor that can be done here so that this is not necessary??

https://github.com/sonatype-nexus-community/nancy/blob/a76019e8e219793dc69cf517029fc554a9d2cf6d/logger/logger.go#L29

https://github.com/sonatype-nexus-community/nancy/blob/a76019e8e219793dc69cf517029fc554a9d2cf6d/logger/logger.go#L75-L80

* **What feature or behavior is this required for?**
Nothing really.....just removing a little ickyness

* **How could we solve this issue? (Not knowing is okay!)**
Maybe conversion to a struct or something where the log directory could be passed in easily. Or something else ¯\_(ツ)_/¯ 

* **Anything else?**

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
I think @bhamail had some cool thoughts here, in that maybe we can pass in a `io.Writer` or something akin and make it a) more easy to test (since you can pass in anything), and kinda take the log directory etc... out of it like you are suggesting.

**Comment by fitzoh** [comment]
I think this one has been resolved?
