### ISSUE TITLE
Give all version info and more to the LogLady

### ISSUE THREAD

**Issue by zendern** [sonatype-nexus-community/nancy#125]
* **What are you trying to do?**
@fitzoh reported issue #124 and even though we have more logging and thats good .... its not super useful to only know that the version was 0.1.17. We could log more details about the actual binary version (all the version info we have). Other details such as os version, cpu architecture,   even what binary cpu architecture nancy is currently being used (32 bit/64 bit version). 

* **What feature or behavior is this required for?**
Better debugging capabilities

* **How could we solve this issue? (Not knowing is okay!)**
LogLady will lead your way  

* **Anything else?**

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
This should be really easy. You can get `runtime.GOOS` for operating system, and `runtime.GOARCH` for architecture.
