### ISSUE TITLE
v1.0.0: Remove old code! Deprecated, old, etc... you are out of here!

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/nancy#126]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
When we get to a `nancy` v1.0.0, let's go through and make sure we get rid of all dead code/deprecated methods, etc...

* **What feature or behavior is this required for?**
It's needed for our long term sanity. Major version release, dump the old stuff that was well meaning but didn't make the long term cut!

* **How could we solve this issue? (Not knowing is okay!)**
Look in the code base for files named `old_*.go` or methods with `Deprecated` in their comments. KILL EM (with kindness)

* **Anything else?**
Have a blast! PRs with all deletions are always fun :)

cc @bhamail / @DarthHater

**Comment by bhamail** [comment]
Fixed by #161
