### ISSUE TITLE
Move common types to a common place

### ISSUE THREAD

**Issue by zendern** [sonatype-nexus-community/nancy#139]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
As mentioned here #138 there are a few common types that we have historically just left in nancy and used elsewhere. It probably time to pull those out into their own thing.  

* **What feature or behavior is this required for?**
Work with someone here to get a new repo/project stood up that will host these common go types/classes. Move that stuff over and fix up imports. 

Other projects that might be impacted
This search should help https://github.com/search?p=4&q=org%3Asonatype-nexus-community+github.com%2Fsonatype-nexus-community%2Fnancy&type=Code

These three as mentioned in #138 appear to be the current list but by the time this is played there might be others. 
Ahab - https://github.com/sonatype-nexus-community/ahab
Cheque - https://github.com/sonatype-nexus-community/cheque 
Hashbrowns - https://github.com/sonatype-nexus-community/hashbrowns

Probably as part of playing this issue we should also create cards in those corresponding repos to switch over the implementation to the common place as well. 

* **How could we solve this issue? (Not knowing is okay!)**
Cut + Paste ;) 

* **Anything else?**
Nah thats its....possible repo name cause why not :) https://github.com/sonatype-nexus-community/go-sona-types

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
This is a thing now!!!

https://github.com/sonatype-nexus-community/go-sona-types

Maybe take a look @zendern and see if I got the important stuff out into that project?

**Comment by bhamail** [comment]
Changes to use go-sona-types library done in #161
