### ISSUE TITLE
Provide option for nancy to auto-update

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/nancy#140]
Would be neat to have nancy (optionally) automatically update itself.

Could take approach similar to that used by CircleCi client. Libs to consider:

https://github.com/rhysd/go-github-selfupdate

https://godoc.org/github.com/tj/go-update

Should use GitHub releases. 

Be aware of handling "brew" installed flavor - I think the CircleCI client handles this.

cc @bhamail / @DarthHater

**Comment by zendern** [comment]
I haven’t used circleci client.... does it really auto do it?? Or is it more of an output that a new version is available and then you call “something something self-upgrade”??

**Comment by bhamail** [comment]
@zendern I could've sworn I saw it just update, but lately it seems to just prompt that there is a new version and you can call “something something self-upgrade”.
