### ISSUE TITLE
Nancy produces invalid JSON again [bug]

### ISSUE THREAD

**Issue by AndreyMZ** [sonatype-nexus-community/nancy#143]
### Steps to reproduce

	cat <<EOF > go.mod
	module backend
	go 1.14
	require (
	    golang.org/x/crypto v0.0.0-20180111101123-5f55bce93ad2
	)
	EOF

	go list -m all | docker run -i sonatypecommunity/nancy:latest -output=json > result.json
	python -m json.tool < result.json
	tail result.json --bytes=40

#### Actual result

	user@pc /cygdrive/c/Users/user/Desktop/test
	$ go list -m all | docker run -i sonatypecommunity/nancy:latest -output=json > result.json

	user@pc /cygdrive/c/Users/user/Desktop/test
	$ python -m json.tool < result.json
	Extra data: line 1 column 2441 - line 2 column 1 (char 2440 - 2460)
	
	user@pc /cygdrive/c/Users/user/Desktop/test
	$ tail result.json --bytes=40
	alidSemVer":false}]}Found vuln count: 1

#### Expected result
No errors on parsing JSON.

### Additional information 1

	user@pc /cygdrive/c/Users/user/Desktop/test
	$ docker run -i sonatypecommunity/nancy:latest -version
	0.2.4
	build time: 2020-05-01T18:19:24Z
	build commit: 91bdb1038cc545a0aaa5db765d3a08f7899ac7a0

### Additional information 2
This is not a first issue about invalid JSON output. The previous one is #90. I think it's worth adding an autotest.

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
Someone threw an errant `fmt.Print` in, and that's what was causing the issue by the looks of it. I just pushed a commit that should address it. Try `v0.2.5` and let me know!

I agree a test would be nice. If you've got some time send a PR over, it might be a bit until I can get some free time to do so!

**Comment by AndreyMZ** [comment]
`v0.2.5` works fine, thank you!
