### ISSUE TITLE
how do i specify OSSINDEX token to nancy iq command?

### ISSUE THREAD

**Issue by th3w4y** [sonatype-nexus-community/nancy#153]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

I am getting and error
``` 
exit code: 3 - Uh oh! There was an error with your request to Nexus IQ Server - error: exit code: 3 - There was an issue auditing packages using OSS Index - error: Post "https://ossindex.sonatype.org/api/v3/component-report": authenticationrequired
```

* **What are you trying to do?**
go list -m all | nancy iq -application XXX -server-url https://nexus-iq -user userCode -token passCode 

* **What feature or behavior is this required for?**
looks like the -token is used by both NexusIQ and OSSIndex? not sure this makes sense?

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

cc @bhamail / @DarthHater

**Comment by th3w4y** [comment]
-token is expected by nexus IQ to auth against itself, iven if i would specify -serverurl in the form https://userCode:passCode@nexusiq

i cannot use ossindex api key as -token in any case...

**Comment by DarthHater** [comment]
Via the command line I don't think we have implemented this quite yet, but if you set your OSS Index config using `nancy config` it SHOULD pick it up. If not, let me know, I or someone will gladly fix it up!

**Comment by th3w4y** [comment]
I awas able to fix it, thanks for your support

**Comment by DarthHater** [comment]
Did setting it with `nancy config` fix it up for you @th3w4y ?

**Comment by th3w4y** [comment]
> Did setting it with `nancy config` fix it up for you @th3w4y ?

I actually cleaned that config and started fresh, so your hint helped me get rid of that I has set there from some time back.
