### ISSUE TITLE
Dependency names are tabbed too far when list of deps hits 3+ digits

### ISSUE THREAD

**Issue by MichelKazi** [sonatype-nexus-community/nancy#154]
* **What are you trying to do?**
It looks like when the dependency index string is too big we get dependencies tabbed over too far, and ends up being worse for the UI in terms of concistency

here's `go list -m all | nancy` on the [hashbrowns](https://github.com/sonatype-nexus-community/hashbrowns) repo:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/34050448/85241779-f9b0af00-b40a-11ea-8578-5ef1ecd84661.png">

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**
I can mess around with whatever I did in tabwriter in my original PR to line these up

cc @bhamail / @DarthHater

**Comment by deadlysyn** [comment]
Hello,

Mind if I tackle this?

PS: Thanks for adding hacktoberfest labels! :sunglasses:

**Comment by zendern** [comment]
> Hello,
> 
> 
> 
> Mind if I tackle this?
> 
> 
> 
> PS: Thanks for adding hacktoberfest labels! :sunglasses: 

Go for it 👍

**Comment by deadlysyn** [comment]
I guess this could be as simple as fixing the Sprintf format strings. Do we need anything more complicated?

One question is, do you think zero-padded or right aligned looks better?

{code}
[0001/0010]     pkg:golang/cloud.google.com/go@0.26.0
[0010/0100]     pkg:golang/cloud.google.com/go@0.26.0
[0100/1000]     pkg:golang/cloud.google.com/go@0.26.0

[   1/  10]     pkg:golang/cloud.google.com/go@0.26.0
[  10/ 100]     pkg:golang/cloud.google.com/go@0.26.0
[ 100/1000]     pkg:golang/cloud.google.com/go@0.26.0
{code}

**Comment by DarthHater** [comment]
The first is pretty hard to read, the second is eh, the third is maybe the best, in how I visually parse them all.

**Comment by deadlysyn** [comment]
One last question before PR... technically we could make it dynamic, so the padding adjusts based on number of purls. That would ensure uniform tabbing + preserve as much screen space as possible at all sizes -- however, we're just talking a couple characters, and it's a form of complexity. Perhaps the bigger win would be working at any project size vs arbitrary guesses as to the right amount of padding (can we have projects with 10000 dependencies? 100000?).

Going dynamic isn't too, but is more to parse when reading the code. Might also be a better way. Somethig like:

{code}
	size := len(strconv.Itoa(packageCount)) // or len(invalidPurls)
	format := fmt.Sprintf("[%%%dd/%%%dd]\t%%s\n", size, size)
	fmt.Sprintf(format, idx, packageCount, au.Bold(...))
{code}

Is this clever or hard to read? Problem with static padding is it'll always look weird at some size. :-)

**Comment by DarthHater** [comment]
Part of me thinks we should just drop the numbers, altogether. I'm not sure if they really add much value. What do y'all think?

**Comment by deadlysyn** [comment]
I don't have enough context to mind either way, but one might feel they're a form of progress bar which is somehow good psychologically when running a large scan...  assuming it's not a bouncy microsoft progress bar. :-D

Does anyone even stare at this often? Is it usually buried in a pipeline somewhere? Maybe the numbers only show up with -v or similar implying a human needs the output?

**Comment by deadlysyn** [comment]
If I don't hear strong objections tomorrow, I'm going to err on the side of "fewer LoC == easier to read == better" (submit PR leaving the numbers out).

**Comment by bhamail** [comment]
I'll second the idea of dropping the 'x of y' numbers. So long as we at least have a "total count" showing somewhere in verbose mode summary, I think can drop the numbers.

A simple "total count" gives a warm fuzzy that we actually did something, and how much we did.

**Comment by MichelKazi** [comment]
I like the sound of not having numbers altogether, and keeping a "total count" at the end
