### ISSUE TITLE
Move Cobra commands into “internal” sub tree.

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/nancy#166]
Putting this is up for discussion. So far, we've been pretty good about using lower case name prefixes to ensure vars and functions in the `cmd` package are non-public. 

It might be better to just move our `cmd` package underneath a package named `internal` to avoid any accidental exposure of private implementation.

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
This likely makes sense, I dunno if there is anything in the commands that someone would want to use in an API.
