### ISSUE TITLE
switch to Go Modules

### ISSUE THREAD

**Issue by arschles** [sonatype-nexus-community/nancy#22]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

Switch from using dep for dependency management to using Go Modules & a module proxy (i.e. [GoNexus](https://gonexus.dev))

* **What feature or behavior is this required for?**

Building the project

* **How could we solve this issue? (Not knowing is okay!)**

Run `go mod init` to migrate from the dep config files, and then verify that the build still works and tests still pass

* **Anything else?**

I'm happy to do this work, if folks are ok with the general idea

**Comment by DarthHater** [comment]
We pretty much already have (we use `go mod` to build Nancy on Travis CI, etc..)! We kept the Gopkg.lock file around mostly because when we started `go mod` was fairly new. If you want to send us a PR with that stuff gone/README updates, we'd love that! Thanks for creating an issue ps!

**Comment by DarthHater** [comment]
One of our team members pointed out that he did some (or maybe all) of this in #12 , wanna jump in there and +1 it, etc...?

**Comment by arschles** [comment]
@DarthHater sorry for the delay. Sure, I'll go +1 #12 :)
