### ISSUE TITLE
Summary should show the number or list of ignored vulnerabilities

### ISSUE THREAD

**Issue by SVilgelm** [sonatype-nexus-community/nancy#232]
right now if the `.nancy-ignore` file contains anything, then the Nancy just silently ignore them, but let at least print the list of ignores in summary. So the CI/CD engineers can see it in the logs of CI jobs.

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
@SVilgelm feel like sending us a PR with this? Not against it!

**Comment by SVilgelm** [comment]
I can do it two weeks later only
