### ISSUE TITLE
TLS Handsake Timeout error

### ISSUE THREAD

**Issue by nurulakbartanjung** [sonatype-nexus-community/nancy#244]
TLS handsake timeout error in CI if i run docker command version latest.

Error: Post "https://ossindex.sonatype.org/api/v3/component-report": net/http: TLS handshake timeout

How to solve it?

**Comment by DarthHater** [comment]
@nurulakbartanjung are you still experiencing this?

**Comment by bhamail** [comment]
closing due to no response. feel free to reopen if needed.
