### ISSUE TITLE
Release on Goreleaser

### ISSUE THREAD

**Issue by mastertinner** [sonatype-nexus-community/nancy#36]
* **What are you trying to do?**

Download a realease from [GoReleaser](https://goreleaser.com/).

* **What feature or behavior is this required for?**

It's very convenient to download releases from there and I think it would also streamline the process of creating releases.

* **How could we solve this issue? (Not knowing is okay!)**

Publish to GoReleaser

* **Anything else?**

cc @bhamail / @DarthHater

**Comment by bhamail** [comment]
Cool. It looks like @nrcook has started work on this in PR #20. Perhaps you could pitch-in there?

**Comment by DarthHater** [comment]
This is now done and live! @mastertinner @bhamail @nrcook closing this!
