### ISSUE TITLE
[Feature request] output option in json format

### ISSUE THREAD

**Issue by th3-j0k3r** [sonatype-nexus-community/nancy#45]
* **What are you trying to do?**
Trying to figure out how to output in json format

* **What feature or behavior is this required for?**
exporting results in json makes parsing and understanding easy and helpful

* **How could we solve this issue? (Not knowing is okay!)**
have an argument like  `--json`

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
Pretty neat! What do you need the json output for? Wondering if we can find a tool that allows you to output to multiple types, not just json.

**Comment by zendern** [comment]
> Pretty neat! What do you need the json output for? Wondering if we can find a tool that allows you to output to multiple types, not just json.

i think you are onto something with multiple types of output. I assume the ask for JSON is to have something that is a little more machine readable make producing a slack message or something like that from the output. But also something that comes to mind is maybe a csv format that could be sent off to security teams when nancy finds a vulnerability.

**Comment by th3-j0k3r** [comment]
The use case I'm looking for is somewhat similar to what @zendern has mentioned. The output in JSON format makes it more readable and with future requirements arising for sending/using this data in JSON format increases flexibility as most languages/frameworks support JSON. Nonetheless, it will be useful to everyone in many use cases. cc @DarthHater

**Comment by zendern** [comment]
Thinking about picking this up some time this week @DarthHater. Probably was going to do something like so. Thoughts??

1. Introduce a new `-output` flag, defaulting to `text` to be backwards compatible.
2. `-output` would allow for the following outputs. `text`, `json`, `csv` and maybe `table`
3. `text` - would look exactly as it does today
4. implementation wise it would just be extracting out what we have currently in [here](https://github.com/sonatype-nexus-community/nancy/blob/master/audit/auditlog.go#L70) to now return a struct. 
5. Using that struct we would simple just create classes to do the different output formats. I know you mentioned finding a library to do it for us but I've yet to find one but should be simple enough to just use mostly what go provides and use what we have. And if we decided `table` makes sense maybe pull in that library. 
- `text` - being what we have in auditlog.go basically
- `json` - using https://golang.org/pkg/encoding/json/ b/c we will just a struct now 
- `csv` - using https://golang.org/pkg/encoding/csv/
- maybe `table` - using https://github.com/olekukonko/tablewriter to give a fancy table formatted output

**Comment by DarthHater** [comment]
All of that sounds great, I'm wondering if we should do HTML instead of table (so someone can create an artifact, similar to CSV). 

I was more curious if you could use logrus to output everything, since it takes different formatters, and can use an `io.Writer`

https://github.com/sirupsen/logrus

**Comment by zendern** [comment]
> All of that sounds great, I'm wondering if we should do HTML instead of table (so someone can create an artifact, similar to CSV).
> 
> I was more curious if you could use logrus to output everything, since it takes different formatters, and can use an `io.Writer`
> 
> https://github.com/sirupsen/logrus

That seems like a reasonable library to try to use. Looking at it on the surface JSON, TEXT, CSV should be pretty straightforward. Whereas an HTML table might be more interesting/harder to do with that library.

**Comment by tweedge** [comment]
Hi! Is there any way that I could lend a hand in getting this merged & released?

**Comment by zendern** [comment]
@tweedge if you want to take a look at the merge conflicts on the pr that would help it along quicker. If not I'll try to get to it some time this week. 

Also a set of eyes/any feedback on the new output formats could help as well to make sure we have what you might need/be looking for.

**Comment by DarthHater** [comment]
I'll see if I can jump in. I'm doing some Nancy work right now anyways, and I'd love to get another @zendern classic merged in :)

**Comment by zendern** [comment]
@DarthHater the merge conflicts in #57 should be good to go now if you want to take a peek.
