### ISSUE TITLE
Temporary vulnerability exclusion

### ISSUE THREAD

**Issue by nathanreynolds-entura** [sonatype-nexus-community/nancy#48]
* **What are you trying to do?**

Temporarily exclude vulnerability checks.

* **What feature or behavior is this required for?**

One of our dependencies has a vulnerability. An upstream fix is forthcoming. We want to temporarily exclude the vulnerability for e.g a month.

* **How could we solve this issue? (Not knowing is okay!)**

For .nancy-ignore perhaps something like:

```
CVE-XYZ # Permanent exclusion
CVE-ABC until=2019-12-01 # Temporary exclusion. On/after 1st December this will be ignored
```

Not sure how this might look for command line arguments.

* **Anything else?**

Happy to work on the code!

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
This would be neat! If you want to take a go at it, would love that.

**Comment by zendern** [comment]
@nathanreynolds-entura did you happen to start to look into this one?? I was considering picking it up if you hadn't started it.
