### ISSUE TITLE
Allow comments in .nancy-ignore

### ISSUE THREAD

**Issue by fitzoh** [sonatype-nexus-community/nancy#51]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Exclude a vulnerability in nancy and make it clear *why* it was ignored

* **What feature or behavior is this required for?**
Allowing future me to know wtf is going on without having to dig into git history

* **How could we solve this issue? (Not knowing is okay!)**
Add comments to .nancy-ignore

* **Anything else?**
Maybe this sort of works already?
Would a "comment" just be an ignored vuln?

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
I doubt this would work by default:

```
		line := strings.TrimSpace(scanner.Text())
		if len(line) > 0 {
			config.CveList.Cves = append(config.CveList.Cves, line)
		}
```

That's the current block that parses the file. We could go a couple different routes with this:

- Make `.nancy-ignore` a yaml, toml, or some other type of file where we could say "Hey just use this schema" and then we could parse it, blah blah blah
- Go the cheap route and just ignore `#` lines or something else like that

Buyers choice!

**Comment by fitzoh** [comment]
>Go the cheap route and just ignore # lines or something else like that

Yeah, that's what I was thinking
