### ISSUE TITLE
Display nancy version by default

### ISSUE THREAD

**Issue by fitzoh** [sonatype-nexus-community/nancy#52]
* **What are you trying to do?**
Display the nancy version for easy debugging

* **What feature or behavior is this required for?**
I'm using nancy from jenkins and the github action, where it's not entirely clear what version of nancy is running.  I don't have an easy way to run `nancy version`, which makes it difficult to debug

* **How could we solve this issue? (Not knowing is okay!)**
By displaying the nancy version for a normal run unless quiet mode is enabled.

* **Anything else?**

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
Yeah, this makes sense! +1
