### ISSUE TITLE
Missing Gopkg.lock causes crash

### ISSUE THREAD

**Issue by flimzy** [sonatype-nexus-community/nancy#58]
In the case that `Gopkg.toml` exists but `Gopkg.lock` does, not, nancy crashes with a nil pointer dereference:

```
Nancy version: development
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x935557]

goroutine 1 [running]:
github.com/sonatype-nexus-community/nancy/packages.ExtractPurlsUsingDep(0xc00002a124, 0x2b, 0xc00002b170, 0x2b, 0xc00002a139, 0x16, 0xc0001749a0, 0x0, 0x0, 0xc00002a139, ...)
        /home/jonhall/go/src/github.com/sonatype-nexus-community/nancy/packages/dep.go:23 +0x37
main.doCheckExistenceAndParse()
        /home/jonhall/go/src/github.com/sonatype-nexus-community/nancy/main.go:102 +0x214
main.main()
        /home/jonhall/go/src/github.com/sonatype-nexus-community/nancy/main.go:63 +0x104
```

To reproduce, create an empty directory containing a `Gopkg.toml` file, then attempt to run nancy.  Example:

```shell
$ mkdir asdf
$ cd asdf
asdf$ touch Gopkg.toml
asdf$ nancy Gopkg.lock
```

**Comment by zendern** [comment]
So the scenario here would be that you have a project that is incorrectly setup (or is this a thing that does happen) and Nancy should instead of bombing at least tell you there is no lock file??

**Comment by flimzy** [comment]
Yes, I think that's about right.  I don't know if it's ever legitimate to have `Gopkg.toml` without `Gopkg.lock` (probably not). But a proper error message seems like the correct behavior.

I'm not sure if this is a problem with nancy, though, or with the `dep` package. I spent a little time debugging, and it may be that `dep` just ignores that case, sending back an incomplete `package` variable to nancy.

**Comment by zendern** [comment]
True... could be a dep “problem” but should be easy enough to guard against with a nil check and a better error message in Nancy.
