### ISSUE TITLE
Switch CI to use Github Actions

### ISSUE THREAD

**Issue by zendern** [sonatype-nexus-community/nancy#66]
* **What are you trying to do?**
Use the cool new hotness in CI tech :) 

* **What feature or behavior is this required for?**
Nothing really .... should be the same output as travis. It might simplify things potentially.

* **How could we solve this issue? (Not knowing is okay!)**
Convert our .travis.yml over to actions. Maybe even use this guy too?? It's not being updated automatically but maybe dogfooding it will make that better at the same time.  '

https://github.com/sonatype-nexus-community/nancy-github-action

There are also lots of prebuilt actions out in the marketplace that might make our CI lives easier. linters, go build setup, etc. That all we have to do is plug them in ¯\_(ツ)_/¯ 

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
I'm not against this, but I would actually like to do CircleCI!

GitHub Actions aren't bad by any means, but my experience using them thus far on another project with Ruby on Rails was less than stellar (they were pretty far behind on versions of Ruby). It essentially put us in a place where we had to write our own Dockerfile and just manage stuff ourselves. Circle has been pretty good overall for the other stuff we work on, and @bhamail / myself are planning on writing a Nancy CircleCI orb this quarter (which we would totally love help on), so it would be cool to dog food it at the same time.

**Comment by zendern** [comment]
So thats cool.... I'll have to read up on CircleCI orbs but I guess my question would be higher level now. How do we make sure that the CI things that are making Nancy easier to use stay up to date?

Maybe #70 helps fix the issue in the github actions case. (https://github.com/sonatype-nexus-community/nancy-github-action)

Maybe the CircleCI Orbs thing is just a docker container again so its fine. But we might want to think about that. Making another repo is clear separation of concerns but if we put that in this project its will just happen as nancy changes. Or at least find a way to get this repo to trigger another ones build. #spitballin

More thinking to do just wanted to throw that out there.

**Comment by DarthHater** [comment]
Yeah the main reason I want to do #70 is because it seems like it will do that, get all the birdies with one stone. Also, we could in theory update other repos as soon as we have a new image, etc... and pin them to it? I need to think about it some more, but I'd love to hear yours and others opinions.

**Comment by zendern** [comment]
No reason to do this....we switched over to CircleCI as @DarthHater mentioned above.
