### ISSUE TITLE
Make nancy not so exit heavy

### ISSUE THREAD

**Issue by zendern** [sonatype-nexus-community/nancy#78]
* **What are you trying to do?**
As part of #68 @DarthHater was trying to do some testing and it the fact that Nancy exits like its going out of style made it overly difficult. 

For now the exits have been put back in place instead of using a panic which made testing easier to do. 

General go guidance is as follows, so this is where we should start to move the codebase. 
```
The convention in the Go libraries is that even when a package uses panic internally, its external API still presents explicit error return values.
```

* **What feature or behavior is this required for?**
No real feature just more of a tech debt/cleanup/make it better type thing.

* **How could we solve this issue? (Not knowing is okay!)**
Stop exiting so much and panic instead but at the same time we still will want to preserve the exit codes and the user friendly messages after this change. No stack trace should be presented to the user. 

* **Anything else?**
¯\_(ツ)_/¯ 

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
@bhamail good issue to tack on to for #134

**Comment by bhamail** [comment]
@DarthHater Agreed. Will do

**Comment by bhamail** [comment]
Working on this here: https://github.com/sonatype-nexus-community/nancy/pull/137
