### ISSUE TITLE
Inconsistency when stdin is from file [bug]

### ISSUE THREAD

**Issue by AndreyMZ** [sonatype-nexus-community/nancy#92]
### Steps to reproduce

1. Try variant 1:

        go list -m all | nancy

2. Try variant 2:

        go list -m all > go-list.txt
        nancy < go-list.txt

#### Actual result
The variant 1 works OK, variant 2 does not work (prints the usage):
~~~
C:\nancy>go list -m all | nancy
<...>
2020/03/11 22:45:54 Nancy version: development
Nancy version: development
[1/38][1mpkg:golang/github.com/AndreasBriese/bbloom@0.0.0-20180913140656-343706a395b7[0m[38;5;251m   No known vulnerabilities against package/version
[0m[2/38][1mpkg:golang/github.com/BurntSushi/toml@0.3.1[0m[38;5;251m   No known vulnerabilities against package/version
<...>
[0m[38/38][1mpkg:golang/github.com/go-yaml/yaml@2.2.2[0m[38;5;251m   No known vulnerabilities against package/version
[0m
Audited dependencies:38,Vulnerable:[1;31m0[0m

C:\nancy>go list -m all > go-list.txt

C:\nancy>nancy < go-list.txt
<...>
2020/03/11 22:46:14 Nancy version: development
Usage:
        go list -m all | nancy [options]
        go list -m all | nancy iq [options]
        nancy [options] </path/to/Gopkg.lock>
        nancy [options] </path/to/go.sum>

Options:
<...>
~~~

#### Expected result
Both variants work identically.

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
Interesting. I am a `cat` abuser so I've definitely not run into this. I'll take a look. Why are you putting it in a file rather than just piping the command (trying to understand the use case)?

**Comment by DarthHater** [comment]
Looks like it's probably related to:

```
	if (fi.Mode() & os.ModeNamedPipe) == 0 {
		flag.Usage()
		os.Exit(1)
	}
```

in main.go, basically it's checking for pipe, not a redirect like you've done.

**Comment by AndreyMZ** [comment]
> Why are you putting it in a file rather than just piping the command (trying to understand the use case)?

1. To review the content of `go-list.txt` before running `nancy`.
2. To save the `go-list.txt` artifact for the future.

**Comment by bhamail** [comment]
Not a solution, but maybe a workaround: pipe the text file into `nancy`:

```
go list -m all > go-list.txt
cat go-list.txt | nancy
```
