### ISSUE TITLE
Simplify Config

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/nancy#95]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

Right now the methods for parsing config (OSS Index and IQ) are largely identical, which is a code smell!

We should endeavor to make these as simple as possible (but no simpler, don't go too wild!)

* **What feature or behavior is this required for?**

Long term code maintainability, right now if we add a common config variable we have two places to deal with it. An example is the verbose flags for the logger.

* **How could we solve this issue? (Not knowing is okay!)**

Buyer's choice! Don't let me hamper your creativity!

* **Anything else?**

AH THE JOYS OF CONFIG!

cc @bhamail / @DarthHater / @zendern / @fitzoh

**Comment by DarthHater** [comment]
@bhamail might actually have this taken care of in #134 , as it handles config, etc... much better, and will simplify a TON of stuff.

**Comment by bhamail** [comment]
Also fixed in #161
